from socketio import base_namespace as base_namespace

class AsyncNamespace(base_namespace.BaseServerNamespace):
    def is_asyncio_based(self): ...
    async def trigger_event(self, event, *args): ...
    async def emit(self, event, data=None, to=None, room=None, skip_sid=None, namespace=None, callback=None, ignore_queue: bool = False): ...
    async def send(self, data, to=None, room=None, skip_sid=None, namespace=None, callback=None, ignore_queue: bool = False): ...
    async def call(self, event, data=None, to=None, sid=None, namespace=None, timeout=None, ignore_queue: bool = False): ...
    async def enter_room(self, sid, room, namespace=None): ...
    async def leave_room(self, sid, room, namespace=None): ...
    async def close_room(self, room, namespace=None): ...
    async def get_session(self, sid, namespace=None): ...
    async def save_session(self, sid, session, namespace=None): ...
    def session(self, sid, namespace=None): ...
    async def disconnect(self, sid, namespace=None): ...

class AsyncClientNamespace(base_namespace.BaseClientNamespace):
    def is_asyncio_based(self): ...
    async def trigger_event(self, event, *args): ...
    async def emit(self, event, data=None, namespace=None, callback=None): ...
    async def send(self, data, namespace=None, callback=None): ...
    async def call(self, event, data=None, namespace=None, timeout=None): ...
    async def disconnect(self): ...
