from _typeshed import Incomplete

class BaseNamespace:
    namespace: Incomplete
    def __init__(self, namespace=None) -> None: ...
    def is_asyncio_based(self): ...

class BaseServerNamespace(BaseNamespace):
    server: Incomplete
    def __init__(self, namespace=None) -> None: ...
    def rooms(self, sid, namespace=None): ...

class BaseClientNamespace(BaseNamespace):
    client: Incomplete
    def __init__(self, namespace=None) -> None: ...
