from . import base_namespace as base_namespace

class Namespace(base_namespace.BaseServerNamespace):
    def trigger_event(self, event, *args): ...
    def emit(self, event, data=None, to=None, room=None, skip_sid=None, namespace=None, callback=None, ignore_queue: bool = False): ...
    def send(self, data, to=None, room=None, skip_sid=None, namespace=None, callback=None, ignore_queue: bool = False): ...
    def call(self, event, data=None, to=None, sid=None, namespace=None, timeout=None, ignore_queue: bool = False): ...
    def enter_room(self, sid, room, namespace=None): ...
    def leave_room(self, sid, room, namespace=None): ...
    def close_room(self, room, namespace=None): ...
    def get_session(self, sid, namespace=None): ...
    def save_session(self, sid, session, namespace=None): ...
    def session(self, sid, namespace=None): ...
    def disconnect(self, sid, namespace=None): ...

class ClientNamespace(base_namespace.BaseClientNamespace):
    def trigger_event(self, event, *args): ...
    def emit(self, event, data=None, namespace=None, callback=None): ...
    def send(self, data, room=None, namespace=None, callback=None): ...
    def call(self, event, data=None, namespace=None, timeout=None): ...
    def disconnect(self): ...
