from .manager import Manager as Manager
from _typeshed import Incomplete

class PubSubManager(Manager):
    name: str
    channel: Incomplete
    write_only: Incomplete
    host_id: Incomplete
    logger: Incomplete
    def __init__(self, channel: str = 'socketio', write_only: bool = False, logger=None) -> None: ...
    thread: Incomplete
    def initialize(self) -> None: ...
    def emit(self, event, data, namespace=None, room=None, skip_sid=None, callback=None, to=None, **kwargs): ...
    def can_disconnect(self, sid, namespace): ...
    def disconnect(self, sid, namespace=None, **kwargs): ...
    def enter_room(self, sid, namespace, room, eio_sid=None): ...
    def leave_room(self, sid, namespace, room): ...
    def close_room(self, room, namespace=None) -> None: ...
