import types
from _typeshed import Incomplete
from socketio import Client as Client
from socketio.exceptions import DisconnectedError as DisconnectedError, SocketIOError as SocketIOError, TimeoutError as TimeoutError

class SimpleClient:
    client_class = Client
    client_args: Incomplete
    client_kwargs: Incomplete
    client: Incomplete
    namespace: str
    connected_event: Incomplete
    connected: bool
    input_event: Incomplete
    input_buffer: Incomplete
    def __init__(self, *args, **kwargs) -> None: ...
    def connect(self, url, headers={}, auth=None, transports=None, namespace: str = '/', socketio_path: str = 'socket.io', wait_timeout: int = 5) -> None: ...
    @property
    def sid(self): ...
    @property
    def transport(self): ...
    def emit(self, event, data=None): ...
    def call(self, event, data=None, timeout: int = 60): ...
    def receive(self, timeout=None): ...
    def disconnect(self) -> None: ...
    def __enter__(self): ...
    def __exit__(self, exc_type: type[BaseException] | None, exc_val: BaseException | None, exc_tb: types.TracebackType | None) -> None: ...
